/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class VitsikaStandaloneSetup extends VitsikaStandaloneSetupGenerated {

	public static void doSetup() {
		new VitsikaStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
