/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.ide.contentassist.antlr.internal.InternalVitsikaParser;
import org.xtext.example.services.VitsikaGrammarAccess;

public class VitsikaParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(VitsikaGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, VitsikaGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getActionAccess().getAlternatives(), "rule__Action__Alternatives");
			builder.put(grammarAccess.getWaitActionAccess().getUnitAlternatives_3_0(), "rule__WaitAction__UnitAlternatives_3_0");
			builder.put(grammarAccess.getAtaovyTaskAccess().getGroup(), "rule__AtaovyTask__Group__0");
			builder.put(grammarAccess.getAtaovyTaskAccess().getGroup_3(), "rule__AtaovyTask__Group_3__0");
			builder.put(grammarAccess.getClickActionAccess().getGroup(), "rule__ClickAction__Group__0");
			builder.put(grammarAccess.getMoveActionAccess().getGroup(), "rule__MoveAction__Group__0");
			builder.put(grammarAccess.getWaitActionAccess().getGroup(), "rule__WaitAction__Group__0");
			builder.put(grammarAccess.getOpenApplicationActionAccess().getGroup(), "rule__OpenApplicationAction__Group__0");
			builder.put(grammarAccess.getOpenApplicationActionAccess().getGroup_3(), "rule__OpenApplicationAction__Group_3__0");
			builder.put(grammarAccess.getMatyAccess().getGroup(), "rule__Maty__Group__0");
			builder.put(grammarAccess.getSurferAccess().getGroup(), "rule__Surfer__Group__0");
			builder.put(grammarAccess.getWifiCreateAccess().getGroup(), "rule__WifiCreate__Group__0");
			builder.put(grammarAccess.getTypewriteAccess().getGroup(), "rule__Typewrite__Group__0");
			builder.put(grammarAccess.getWordTypingAutoAccess().getGroup(), "rule__WordTypingAuto__Group__0");
			builder.put(grammarAccess.getModelAccess().getTaskAssignment(), "rule__Model__TaskAssignment");
			builder.put(grammarAccess.getAtaovyTaskAccess().getActionsAssignment_2(), "rule__AtaovyTask__ActionsAssignment_2");
			builder.put(grammarAccess.getAtaovyTaskAccess().getActionsAssignment_3_1(), "rule__AtaovyTask__ActionsAssignment_3_1");
			builder.put(grammarAccess.getClickActionAccess().getKeyAssignment_2(), "rule__ClickAction__KeyAssignment_2");
			builder.put(grammarAccess.getMoveActionAccess().getXAssignment_2(), "rule__MoveAction__XAssignment_2");
			builder.put(grammarAccess.getMoveActionAccess().getYAssignment_4(), "rule__MoveAction__YAssignment_4");
			builder.put(grammarAccess.getWaitActionAccess().getDurationAssignment_2(), "rule__WaitAction__DurationAssignment_2");
			builder.put(grammarAccess.getWaitActionAccess().getUnitAssignment_3(), "rule__WaitAction__UnitAssignment_3");
			builder.put(grammarAccess.getOpenApplicationActionAccess().getApplicationsAssignment_2(), "rule__OpenApplicationAction__ApplicationsAssignment_2");
			builder.put(grammarAccess.getOpenApplicationActionAccess().getApplicationsAssignment_3_1(), "rule__OpenApplicationAction__ApplicationsAssignment_3_1");
			builder.put(grammarAccess.getMatyAccess().getProcAssignment_2(), "rule__Maty__ProcAssignment_2");
			builder.put(grammarAccess.getSurferAccess().getUrlAssignment_2(), "rule__Surfer__UrlAssignment_2");
			builder.put(grammarAccess.getWifiCreateAccess().getSsidAssignment_2(), "rule__WifiCreate__SsidAssignment_2");
			builder.put(grammarAccess.getWifiCreateAccess().getPasswdAssignment_4(), "rule__WifiCreate__PasswdAssignment_4");
			builder.put(grammarAccess.getTypewriteAccess().getSoratraAssignment_2(), "rule__Typewrite__SoratraAssignment_2");
			builder.put(grammarAccess.getWordTypingAutoAccess().getTenyAssignment_2(), "rule__WordTypingAuto__TenyAssignment_2");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private VitsikaGrammarAccess grammarAccess;

	@Override
	protected InternalVitsikaParser createParser() {
		InternalVitsikaParser result = new InternalVitsikaParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public VitsikaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(VitsikaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
