/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.vitsika.impl;

import java.util.Collection;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.util.EDataTypeEList;

import org.xtext.example.vitsika.OpenApplicationAction;
import org.xtext.example.vitsika.VitsikaPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Open Application Action</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.vitsika.impl.OpenApplicationActionImpl#getApplications <em>Applications</em>}</li>
 * </ul>
 *
 * @generated
 */
public class OpenApplicationActionImpl extends ActionImpl implements OpenApplicationAction
{
  /**
   * The cached value of the '{@link #getApplications() <em>Applications</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getApplications()
   * @generated
   * @ordered
   */
  protected EList<String> applications;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OpenApplicationActionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return VitsikaPackage.Literals.OPEN_APPLICATION_ACTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getApplications()
  {
    if (applications == null)
    {
      applications = new EDataTypeEList<String>(String.class, this, VitsikaPackage.OPEN_APPLICATION_ACTION__APPLICATIONS);
    }
    return applications;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case VitsikaPackage.OPEN_APPLICATION_ACTION__APPLICATIONS:
        return getApplications();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case VitsikaPackage.OPEN_APPLICATION_ACTION__APPLICATIONS:
        getApplications().clear();
        getApplications().addAll((Collection<? extends String>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case VitsikaPackage.OPEN_APPLICATION_ACTION__APPLICATIONS:
        getApplications().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case VitsikaPackage.OPEN_APPLICATION_ACTION__APPLICATIONS:
        return applications != null && !applications.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (applications: ");
    result.append(applications);
    result.append(')');
    return result.toString();
  }

} //OpenApplicationActionImpl
