/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.vitsika.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.xtext.example.vitsika.Action;
import org.xtext.example.vitsika.AtaovyTask;
import org.xtext.example.vitsika.ClickAction;
import org.xtext.example.vitsika.Maty;
import org.xtext.example.vitsika.Model;
import org.xtext.example.vitsika.MoveAction;
import org.xtext.example.vitsika.OpenApplicationAction;
import org.xtext.example.vitsika.Surfer;
import org.xtext.example.vitsika.Typewrite;
import org.xtext.example.vitsika.VitsikaFactory;
import org.xtext.example.vitsika.VitsikaPackage;
import org.xtext.example.vitsika.WaitAction;
import org.xtext.example.vitsika.WifiCreate;
import org.xtext.example.vitsika.WordTypingAuto;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class VitsikaPackageImpl extends EPackageImpl implements VitsikaPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass ataovyTaskEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass actionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass clickActionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass moveActionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass waitActionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass openApplicationActionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass matyEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass surferEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass wifiCreateEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass typewriteEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass wordTypingAutoEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see org.xtext.example.vitsika.VitsikaPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private VitsikaPackageImpl()
  {
    super(eNS_URI, VitsikaFactory.eINSTANCE);
  }
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link VitsikaPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static VitsikaPackage init()
  {
    if (isInited) return (VitsikaPackage)EPackage.Registry.INSTANCE.getEPackage(VitsikaPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredVitsikaPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    VitsikaPackageImpl theVitsikaPackage = registeredVitsikaPackage instanceof VitsikaPackageImpl ? (VitsikaPackageImpl)registeredVitsikaPackage : new VitsikaPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theVitsikaPackage.createPackageContents();

    // Initialize created meta-data
    theVitsikaPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theVitsikaPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(VitsikaPackage.eNS_URI, theVitsikaPackage);
    return theVitsikaPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getModel()
  {
    return modelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModel_Task()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAtaovyTask()
  {
    return ataovyTaskEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAtaovyTask_Actions()
  {
    return (EReference)ataovyTaskEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAction()
  {
    return actionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getClickAction()
  {
    return clickActionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getClickAction_Key()
  {
    return (EAttribute)clickActionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMoveAction()
  {
    return moveActionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMoveAction_X()
  {
    return (EAttribute)moveActionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMoveAction_Y()
  {
    return (EAttribute)moveActionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getWaitAction()
  {
    return waitActionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getWaitAction_Duration()
  {
    return (EAttribute)waitActionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getWaitAction_Unit()
  {
    return (EAttribute)waitActionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getOpenApplicationAction()
  {
    return openApplicationActionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getOpenApplicationAction_Applications()
  {
    return (EAttribute)openApplicationActionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMaty()
  {
    return matyEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMaty_Proc()
  {
    return (EAttribute)matyEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSurfer()
  {
    return surferEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSurfer_Url()
  {
    return (EAttribute)surferEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getWifiCreate()
  {
    return wifiCreateEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getWifiCreate_Ssid()
  {
    return (EAttribute)wifiCreateEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getWifiCreate_Passwd()
  {
    return (EAttribute)wifiCreateEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getTypewrite()
  {
    return typewriteEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getTypewrite_Soratra()
  {
    return (EAttribute)typewriteEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getWordTypingAuto()
  {
    return wordTypingAutoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getWordTypingAuto_Teny()
  {
    return (EAttribute)wordTypingAutoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public VitsikaFactory getVitsikaFactory()
  {
    return (VitsikaFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    modelEClass = createEClass(MODEL);
    createEReference(modelEClass, MODEL__TASK);

    ataovyTaskEClass = createEClass(ATAOVY_TASK);
    createEReference(ataovyTaskEClass, ATAOVY_TASK__ACTIONS);

    actionEClass = createEClass(ACTION);

    clickActionEClass = createEClass(CLICK_ACTION);
    createEAttribute(clickActionEClass, CLICK_ACTION__KEY);

    moveActionEClass = createEClass(MOVE_ACTION);
    createEAttribute(moveActionEClass, MOVE_ACTION__X);
    createEAttribute(moveActionEClass, MOVE_ACTION__Y);

    waitActionEClass = createEClass(WAIT_ACTION);
    createEAttribute(waitActionEClass, WAIT_ACTION__DURATION);
    createEAttribute(waitActionEClass, WAIT_ACTION__UNIT);

    openApplicationActionEClass = createEClass(OPEN_APPLICATION_ACTION);
    createEAttribute(openApplicationActionEClass, OPEN_APPLICATION_ACTION__APPLICATIONS);

    matyEClass = createEClass(MATY);
    createEAttribute(matyEClass, MATY__PROC);

    surferEClass = createEClass(SURFER);
    createEAttribute(surferEClass, SURFER__URL);

    wifiCreateEClass = createEClass(WIFI_CREATE);
    createEAttribute(wifiCreateEClass, WIFI_CREATE__SSID);
    createEAttribute(wifiCreateEClass, WIFI_CREATE__PASSWD);

    typewriteEClass = createEClass(TYPEWRITE);
    createEAttribute(typewriteEClass, TYPEWRITE__SORATRA);

    wordTypingAutoEClass = createEClass(WORD_TYPING_AUTO);
    createEAttribute(wordTypingAutoEClass, WORD_TYPING_AUTO__TENY);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    clickActionEClass.getESuperTypes().add(this.getAction());
    moveActionEClass.getESuperTypes().add(this.getAction());
    waitActionEClass.getESuperTypes().add(this.getAction());
    openApplicationActionEClass.getESuperTypes().add(this.getAction());
    matyEClass.getESuperTypes().add(this.getAction());
    surferEClass.getESuperTypes().add(this.getAction());
    wifiCreateEClass.getESuperTypes().add(this.getAction());
    typewriteEClass.getESuperTypes().add(this.getAction());
    wordTypingAutoEClass.getESuperTypes().add(this.getAction());

    // Initialize classes and features; add operations and parameters
    initEClass(modelEClass, Model.class, "Model", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getModel_Task(), this.getAtaovyTask(), null, "task", null, 0, 1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(ataovyTaskEClass, AtaovyTask.class, "AtaovyTask", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getAtaovyTask_Actions(), this.getAction(), null, "actions", null, 0, -1, AtaovyTask.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(actionEClass, Action.class, "Action", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(clickActionEClass, ClickAction.class, "ClickAction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getClickAction_Key(), ecorePackage.getEString(), "key", null, 0, 1, ClickAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(moveActionEClass, MoveAction.class, "MoveAction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMoveAction_X(), ecorePackage.getEInt(), "X", null, 0, 1, MoveAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMoveAction_Y(), ecorePackage.getEInt(), "Y", null, 0, 1, MoveAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(waitActionEClass, WaitAction.class, "WaitAction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getWaitAction_Duration(), ecorePackage.getEInt(), "duration", null, 0, 1, WaitAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getWaitAction_Unit(), ecorePackage.getEString(), "unit", null, 0, 1, WaitAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(openApplicationActionEClass, OpenApplicationAction.class, "OpenApplicationAction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getOpenApplicationAction_Applications(), ecorePackage.getEString(), "applications", null, 0, -1, OpenApplicationAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(matyEClass, Maty.class, "Maty", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMaty_Proc(), ecorePackage.getEString(), "proc", null, 0, 1, Maty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(surferEClass, Surfer.class, "Surfer", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSurfer_Url(), ecorePackage.getEString(), "url", null, 0, 1, Surfer.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(wifiCreateEClass, WifiCreate.class, "WifiCreate", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getWifiCreate_Ssid(), ecorePackage.getEString(), "ssid", null, 0, 1, WifiCreate.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getWifiCreate_Passwd(), ecorePackage.getEString(), "passwd", null, 0, 1, WifiCreate.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(typewriteEClass, Typewrite.class, "Typewrite", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getTypewrite_Soratra(), ecorePackage.getEString(), "soratra", null, 0, 1, Typewrite.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(wordTypingAutoEClass, WordTypingAuto.class, "WordTypingAuto", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getWordTypingAuto_Teny(), ecorePackage.getEString(), "teny", null, 0, 1, WordTypingAuto.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //VitsikaPackageImpl
