/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.vitsika.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.example.vitsika.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class VitsikaFactoryImpl extends EFactoryImpl implements VitsikaFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static VitsikaFactory init()
  {
    try
    {
      VitsikaFactory theVitsikaFactory = (VitsikaFactory)EPackage.Registry.INSTANCE.getEFactory(VitsikaPackage.eNS_URI);
      if (theVitsikaFactory != null)
      {
        return theVitsikaFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new VitsikaFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public VitsikaFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case VitsikaPackage.MODEL: return createModel();
      case VitsikaPackage.ATAOVY_TASK: return createAtaovyTask();
      case VitsikaPackage.ACTION: return createAction();
      case VitsikaPackage.CLICK_ACTION: return createClickAction();
      case VitsikaPackage.MOVE_ACTION: return createMoveAction();
      case VitsikaPackage.WAIT_ACTION: return createWaitAction();
      case VitsikaPackage.OPEN_APPLICATION_ACTION: return createOpenApplicationAction();
      case VitsikaPackage.MATY: return createMaty();
      case VitsikaPackage.SURFER: return createSurfer();
      case VitsikaPackage.WIFI_CREATE: return createWifiCreate();
      case VitsikaPackage.TYPEWRITE: return createTypewrite();
      case VitsikaPackage.WORD_TYPING_AUTO: return createWordTypingAuto();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Model createModel()
  {
    ModelImpl model = new ModelImpl();
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AtaovyTask createAtaovyTask()
  {
    AtaovyTaskImpl ataovyTask = new AtaovyTaskImpl();
    return ataovyTask;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Action createAction()
  {
    ActionImpl action = new ActionImpl();
    return action;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ClickAction createClickAction()
  {
    ClickActionImpl clickAction = new ClickActionImpl();
    return clickAction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MoveAction createMoveAction()
  {
    MoveActionImpl moveAction = new MoveActionImpl();
    return moveAction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public WaitAction createWaitAction()
  {
    WaitActionImpl waitAction = new WaitActionImpl();
    return waitAction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OpenApplicationAction createOpenApplicationAction()
  {
    OpenApplicationActionImpl openApplicationAction = new OpenApplicationActionImpl();
    return openApplicationAction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Maty createMaty()
  {
    MatyImpl maty = new MatyImpl();
    return maty;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Surfer createSurfer()
  {
    SurferImpl surfer = new SurferImpl();
    return surfer;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public WifiCreate createWifiCreate()
  {
    WifiCreateImpl wifiCreate = new WifiCreateImpl();
    return wifiCreate;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Typewrite createTypewrite()
  {
    TypewriteImpl typewrite = new TypewriteImpl();
    return typewrite;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public WordTypingAuto createWordTypingAuto()
  {
    WordTypingAutoImpl wordTypingAuto = new WordTypingAutoImpl();
    return wordTypingAuto;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public VitsikaPackage getVitsikaPackage()
  {
    return (VitsikaPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static VitsikaPackage getPackage()
  {
    return VitsikaPackage.eINSTANCE;
  }

} //VitsikaFactoryImpl
