/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.vitsika.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.vitsika.VitsikaPackage;
import org.xtext.example.vitsika.WordTypingAuto;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Word Typing Auto</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.vitsika.impl.WordTypingAutoImpl#getTeny <em>Teny</em>}</li>
 * </ul>
 *
 * @generated
 */
public class WordTypingAutoImpl extends ActionImpl implements WordTypingAuto
{
  /**
   * The default value of the '{@link #getTeny() <em>Teny</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTeny()
   * @generated
   * @ordered
   */
  protected static final String TENY_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTeny() <em>Teny</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTeny()
   * @generated
   * @ordered
   */
  protected String teny = TENY_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected WordTypingAutoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return VitsikaPackage.Literals.WORD_TYPING_AUTO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTeny()
  {
    return teny;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTeny(String newTeny)
  {
    String oldTeny = teny;
    teny = newTeny;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VitsikaPackage.WORD_TYPING_AUTO__TENY, oldTeny, teny));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case VitsikaPackage.WORD_TYPING_AUTO__TENY:
        return getTeny();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case VitsikaPackage.WORD_TYPING_AUTO__TENY:
        setTeny((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case VitsikaPackage.WORD_TYPING_AUTO__TENY:
        setTeny(TENY_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case VitsikaPackage.WORD_TYPING_AUTO__TENY:
        return TENY_EDEFAULT == null ? teny != null : !TENY_EDEFAULT.equals(teny);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (teny: ");
    result.append(teny);
    result.append(')');
    return result.toString();
  }

} //WordTypingAutoImpl
