/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.Vitsika.ui.internal.VitsikaActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class VitsikaExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(VitsikaActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		VitsikaActivator activator = VitsikaActivator.getInstance();
		return activator != null ? activator.getInjector(VitsikaActivator.ORG_XTEXT_EXAMPLE_VITSIKA) : null;
	}

}
