/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.parser.antlr.internal.InternalVitsikaParser;
import org.xtext.example.services.VitsikaGrammarAccess;

public class VitsikaParser extends AbstractAntlrParser {

	@Inject
	private VitsikaGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalVitsikaParser createParser(XtextTokenStream stream) {
		return new InternalVitsikaParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public VitsikaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(VitsikaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
