/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.vitsika;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ataovy Task</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.vitsika.AtaovyTask#getActions <em>Actions</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.vitsika.VitsikaPackage#getAtaovyTask()
 * @model
 * @generated
 */
public interface AtaovyTask extends EObject
{
  /**
   * Returns the value of the '<em><b>Actions</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.vitsika.Action}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actions</em>' containment reference list.
   * @see org.xtext.example.vitsika.VitsikaPackage#getAtaovyTask_Actions()
   * @model containment="true"
   * @generated
   */
  EList<Action> getActions();

} // AtaovyTask
