/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.vitsika;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Maty</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.vitsika.Maty#getProc <em>Proc</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.vitsika.VitsikaPackage#getMaty()
 * @model
 * @generated
 */
public interface Maty extends Action
{
  /**
   * Returns the value of the '<em><b>Proc</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Proc</em>' attribute.
   * @see #setProc(String)
   * @see org.xtext.example.vitsika.VitsikaPackage#getMaty_Proc()
   * @model
   * @generated
   */
  String getProc();

  /**
   * Sets the value of the '{@link org.xtext.example.vitsika.Maty#getProc <em>Proc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Proc</em>' attribute.
   * @see #getProc()
   * @generated
   */
  void setProc(String value);

} // Maty
