/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.vitsika;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.vitsika.Model#getTask <em>Task</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.vitsika.VitsikaPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Task</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Task</em>' containment reference.
   * @see #setTask(AtaovyTask)
   * @see org.xtext.example.vitsika.VitsikaPackage#getModel_Task()
   * @model containment="true"
   * @generated
   */
  AtaovyTask getTask();

  /**
   * Sets the value of the '{@link org.xtext.example.vitsika.Model#getTask <em>Task</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Task</em>' containment reference.
   * @see #getTask()
   * @generated
   */
  void setTask(AtaovyTask value);

} // Model
