/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.vitsika;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Open Application Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.vitsika.OpenApplicationAction#getApplications <em>Applications</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.vitsika.VitsikaPackage#getOpenApplicationAction()
 * @model
 * @generated
 */
public interface OpenApplicationAction extends Action
{
  /**
   * Returns the value of the '<em><b>Applications</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Applications</em>' attribute list.
   * @see org.xtext.example.vitsika.VitsikaPackage#getOpenApplicationAction_Applications()
   * @model unique="false"
   * @generated
   */
  EList<String> getApplications();

} // OpenApplicationAction
