/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.vitsika;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Typewrite</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.vitsika.Typewrite#getSoratra <em>Soratra</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.vitsika.VitsikaPackage#getTypewrite()
 * @model
 * @generated
 */
public interface Typewrite extends Action
{
  /**
   * Returns the value of the '<em><b>Soratra</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Soratra</em>' attribute.
   * @see #setSoratra(String)
   * @see org.xtext.example.vitsika.VitsikaPackage#getTypewrite_Soratra()
   * @model
   * @generated
   */
  String getSoratra();

  /**
   * Sets the value of the '{@link org.xtext.example.vitsika.Typewrite#getSoratra <em>Soratra</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Soratra</em>' attribute.
   * @see #getSoratra()
   * @generated
   */
  void setSoratra(String value);

} // Typewrite
