/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.vitsika;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.vitsika.VitsikaFactory
 * @model kind="package"
 * @generated
 */
public interface VitsikaPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "vitsika";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/Vitsika";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "vitsika";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  VitsikaPackage eINSTANCE = org.xtext.example.vitsika.impl.VitsikaPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.vitsika.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.vitsika.impl.ModelImpl
   * @see org.xtext.example.vitsika.impl.VitsikaPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Task</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__TASK = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.vitsika.impl.AtaovyTaskImpl <em>Ataovy Task</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.vitsika.impl.AtaovyTaskImpl
   * @see org.xtext.example.vitsika.impl.VitsikaPackageImpl#getAtaovyTask()
   * @generated
   */
  int ATAOVY_TASK = 1;

  /**
   * The feature id for the '<em><b>Actions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATAOVY_TASK__ACTIONS = 0;

  /**
   * The number of structural features of the '<em>Ataovy Task</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATAOVY_TASK_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.vitsika.impl.ActionImpl <em>Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.vitsika.impl.ActionImpl
   * @see org.xtext.example.vitsika.impl.VitsikaPackageImpl#getAction()
   * @generated
   */
  int ACTION = 2;

  /**
   * The number of structural features of the '<em>Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.vitsika.impl.ClickActionImpl <em>Click Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.vitsika.impl.ClickActionImpl
   * @see org.xtext.example.vitsika.impl.VitsikaPackageImpl#getClickAction()
   * @generated
   */
  int CLICK_ACTION = 3;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK_ACTION__KEY = ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Click Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK_ACTION_FEATURE_COUNT = ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.vitsika.impl.MoveActionImpl <em>Move Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.vitsika.impl.MoveActionImpl
   * @see org.xtext.example.vitsika.impl.VitsikaPackageImpl#getMoveAction()
   * @generated
   */
  int MOVE_ACTION = 4;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_ACTION__X = ACTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_ACTION__Y = ACTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Move Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_ACTION_FEATURE_COUNT = ACTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.vitsika.impl.WaitActionImpl <em>Wait Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.vitsika.impl.WaitActionImpl
   * @see org.xtext.example.vitsika.impl.VitsikaPackageImpl#getWaitAction()
   * @generated
   */
  int WAIT_ACTION = 5;

  /**
   * The feature id for the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WAIT_ACTION__DURATION = ACTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Unit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WAIT_ACTION__UNIT = ACTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Wait Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WAIT_ACTION_FEATURE_COUNT = ACTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.vitsika.impl.OpenApplicationActionImpl <em>Open Application Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.vitsika.impl.OpenApplicationActionImpl
   * @see org.xtext.example.vitsika.impl.VitsikaPackageImpl#getOpenApplicationAction()
   * @generated
   */
  int OPEN_APPLICATION_ACTION = 6;

  /**
   * The feature id for the '<em><b>Applications</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPEN_APPLICATION_ACTION__APPLICATIONS = ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Open Application Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPEN_APPLICATION_ACTION_FEATURE_COUNT = ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.vitsika.impl.MatyImpl <em>Maty</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.vitsika.impl.MatyImpl
   * @see org.xtext.example.vitsika.impl.VitsikaPackageImpl#getMaty()
   * @generated
   */
  int MATY = 7;

  /**
   * The feature id for the '<em><b>Proc</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATY__PROC = ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Maty</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATY_FEATURE_COUNT = ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.vitsika.impl.SurferImpl <em>Surfer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.vitsika.impl.SurferImpl
   * @see org.xtext.example.vitsika.impl.VitsikaPackageImpl#getSurfer()
   * @generated
   */
  int SURFER = 8;

  /**
   * The feature id for the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SURFER__URL = ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Surfer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SURFER_FEATURE_COUNT = ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.vitsika.impl.WifiCreateImpl <em>Wifi Create</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.vitsika.impl.WifiCreateImpl
   * @see org.xtext.example.vitsika.impl.VitsikaPackageImpl#getWifiCreate()
   * @generated
   */
  int WIFI_CREATE = 9;

  /**
   * The feature id for the '<em><b>Ssid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WIFI_CREATE__SSID = ACTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Passwd</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WIFI_CREATE__PASSWD = ACTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Wifi Create</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WIFI_CREATE_FEATURE_COUNT = ACTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.vitsika.impl.TypewriteImpl <em>Typewrite</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.vitsika.impl.TypewriteImpl
   * @see org.xtext.example.vitsika.impl.VitsikaPackageImpl#getTypewrite()
   * @generated
   */
  int TYPEWRITE = 10;

  /**
   * The feature id for the '<em><b>Soratra</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPEWRITE__SORATRA = ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Typewrite</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPEWRITE_FEATURE_COUNT = ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.vitsika.impl.WordTypingAutoImpl <em>Word Typing Auto</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.vitsika.impl.WordTypingAutoImpl
   * @see org.xtext.example.vitsika.impl.VitsikaPackageImpl#getWordTypingAuto()
   * @generated
   */
  int WORD_TYPING_AUTO = 11;

  /**
   * The feature id for the '<em><b>Teny</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORD_TYPING_AUTO__TENY = ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Word Typing Auto</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORD_TYPING_AUTO_FEATURE_COUNT = ACTION_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.vitsika.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.vitsika.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.vitsika.Model#getTask <em>Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Task</em>'.
   * @see org.xtext.example.vitsika.Model#getTask()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Task();

  /**
   * Returns the meta object for class '{@link org.xtext.example.vitsika.AtaovyTask <em>Ataovy Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ataovy Task</em>'.
   * @see org.xtext.example.vitsika.AtaovyTask
   * @generated
   */
  EClass getAtaovyTask();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.vitsika.AtaovyTask#getActions <em>Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Actions</em>'.
   * @see org.xtext.example.vitsika.AtaovyTask#getActions()
   * @see #getAtaovyTask()
   * @generated
   */
  EReference getAtaovyTask_Actions();

  /**
   * Returns the meta object for class '{@link org.xtext.example.vitsika.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action</em>'.
   * @see org.xtext.example.vitsika.Action
   * @generated
   */
  EClass getAction();

  /**
   * Returns the meta object for class '{@link org.xtext.example.vitsika.ClickAction <em>Click Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Click Action</em>'.
   * @see org.xtext.example.vitsika.ClickAction
   * @generated
   */
  EClass getClickAction();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.vitsika.ClickAction#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see org.xtext.example.vitsika.ClickAction#getKey()
   * @see #getClickAction()
   * @generated
   */
  EAttribute getClickAction_Key();

  /**
   * Returns the meta object for class '{@link org.xtext.example.vitsika.MoveAction <em>Move Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Move Action</em>'.
   * @see org.xtext.example.vitsika.MoveAction
   * @generated
   */
  EClass getMoveAction();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.vitsika.MoveAction#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see org.xtext.example.vitsika.MoveAction#getX()
   * @see #getMoveAction()
   * @generated
   */
  EAttribute getMoveAction_X();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.vitsika.MoveAction#getY <em>Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Y</em>'.
   * @see org.xtext.example.vitsika.MoveAction#getY()
   * @see #getMoveAction()
   * @generated
   */
  EAttribute getMoveAction_Y();

  /**
   * Returns the meta object for class '{@link org.xtext.example.vitsika.WaitAction <em>Wait Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Wait Action</em>'.
   * @see org.xtext.example.vitsika.WaitAction
   * @generated
   */
  EClass getWaitAction();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.vitsika.WaitAction#getDuration <em>Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Duration</em>'.
   * @see org.xtext.example.vitsika.WaitAction#getDuration()
   * @see #getWaitAction()
   * @generated
   */
  EAttribute getWaitAction_Duration();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.vitsika.WaitAction#getUnit <em>Unit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Unit</em>'.
   * @see org.xtext.example.vitsika.WaitAction#getUnit()
   * @see #getWaitAction()
   * @generated
   */
  EAttribute getWaitAction_Unit();

  /**
   * Returns the meta object for class '{@link org.xtext.example.vitsika.OpenApplicationAction <em>Open Application Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Open Application Action</em>'.
   * @see org.xtext.example.vitsika.OpenApplicationAction
   * @generated
   */
  EClass getOpenApplicationAction();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.vitsika.OpenApplicationAction#getApplications <em>Applications</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Applications</em>'.
   * @see org.xtext.example.vitsika.OpenApplicationAction#getApplications()
   * @see #getOpenApplicationAction()
   * @generated
   */
  EAttribute getOpenApplicationAction_Applications();

  /**
   * Returns the meta object for class '{@link org.xtext.example.vitsika.Maty <em>Maty</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Maty</em>'.
   * @see org.xtext.example.vitsika.Maty
   * @generated
   */
  EClass getMaty();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.vitsika.Maty#getProc <em>Proc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Proc</em>'.
   * @see org.xtext.example.vitsika.Maty#getProc()
   * @see #getMaty()
   * @generated
   */
  EAttribute getMaty_Proc();

  /**
   * Returns the meta object for class '{@link org.xtext.example.vitsika.Surfer <em>Surfer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Surfer</em>'.
   * @see org.xtext.example.vitsika.Surfer
   * @generated
   */
  EClass getSurfer();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.vitsika.Surfer#getUrl <em>Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Url</em>'.
   * @see org.xtext.example.vitsika.Surfer#getUrl()
   * @see #getSurfer()
   * @generated
   */
  EAttribute getSurfer_Url();

  /**
   * Returns the meta object for class '{@link org.xtext.example.vitsika.WifiCreate <em>Wifi Create</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Wifi Create</em>'.
   * @see org.xtext.example.vitsika.WifiCreate
   * @generated
   */
  EClass getWifiCreate();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.vitsika.WifiCreate#getSsid <em>Ssid</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ssid</em>'.
   * @see org.xtext.example.vitsika.WifiCreate#getSsid()
   * @see #getWifiCreate()
   * @generated
   */
  EAttribute getWifiCreate_Ssid();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.vitsika.WifiCreate#getPasswd <em>Passwd</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Passwd</em>'.
   * @see org.xtext.example.vitsika.WifiCreate#getPasswd()
   * @see #getWifiCreate()
   * @generated
   */
  EAttribute getWifiCreate_Passwd();

  /**
   * Returns the meta object for class '{@link org.xtext.example.vitsika.Typewrite <em>Typewrite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Typewrite</em>'.
   * @see org.xtext.example.vitsika.Typewrite
   * @generated
   */
  EClass getTypewrite();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.vitsika.Typewrite#getSoratra <em>Soratra</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Soratra</em>'.
   * @see org.xtext.example.vitsika.Typewrite#getSoratra()
   * @see #getTypewrite()
   * @generated
   */
  EAttribute getTypewrite_Soratra();

  /**
   * Returns the meta object for class '{@link org.xtext.example.vitsika.WordTypingAuto <em>Word Typing Auto</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Word Typing Auto</em>'.
   * @see org.xtext.example.vitsika.WordTypingAuto
   * @generated
   */
  EClass getWordTypingAuto();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.vitsika.WordTypingAuto#getTeny <em>Teny</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Teny</em>'.
   * @see org.xtext.example.vitsika.WordTypingAuto#getTeny()
   * @see #getWordTypingAuto()
   * @generated
   */
  EAttribute getWordTypingAuto_Teny();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  VitsikaFactory getVitsikaFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.vitsika.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.vitsika.impl.ModelImpl
     * @see org.xtext.example.vitsika.impl.VitsikaPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Task</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__TASK = eINSTANCE.getModel_Task();

    /**
     * The meta object literal for the '{@link org.xtext.example.vitsika.impl.AtaovyTaskImpl <em>Ataovy Task</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.vitsika.impl.AtaovyTaskImpl
     * @see org.xtext.example.vitsika.impl.VitsikaPackageImpl#getAtaovyTask()
     * @generated
     */
    EClass ATAOVY_TASK = eINSTANCE.getAtaovyTask();

    /**
     * The meta object literal for the '<em><b>Actions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATAOVY_TASK__ACTIONS = eINSTANCE.getAtaovyTask_Actions();

    /**
     * The meta object literal for the '{@link org.xtext.example.vitsika.impl.ActionImpl <em>Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.vitsika.impl.ActionImpl
     * @see org.xtext.example.vitsika.impl.VitsikaPackageImpl#getAction()
     * @generated
     */
    EClass ACTION = eINSTANCE.getAction();

    /**
     * The meta object literal for the '{@link org.xtext.example.vitsika.impl.ClickActionImpl <em>Click Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.vitsika.impl.ClickActionImpl
     * @see org.xtext.example.vitsika.impl.VitsikaPackageImpl#getClickAction()
     * @generated
     */
    EClass CLICK_ACTION = eINSTANCE.getClickAction();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLICK_ACTION__KEY = eINSTANCE.getClickAction_Key();

    /**
     * The meta object literal for the '{@link org.xtext.example.vitsika.impl.MoveActionImpl <em>Move Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.vitsika.impl.MoveActionImpl
     * @see org.xtext.example.vitsika.impl.VitsikaPackageImpl#getMoveAction()
     * @generated
     */
    EClass MOVE_ACTION = eINSTANCE.getMoveAction();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOVE_ACTION__X = eINSTANCE.getMoveAction_X();

    /**
     * The meta object literal for the '<em><b>Y</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOVE_ACTION__Y = eINSTANCE.getMoveAction_Y();

    /**
     * The meta object literal for the '{@link org.xtext.example.vitsika.impl.WaitActionImpl <em>Wait Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.vitsika.impl.WaitActionImpl
     * @see org.xtext.example.vitsika.impl.VitsikaPackageImpl#getWaitAction()
     * @generated
     */
    EClass WAIT_ACTION = eINSTANCE.getWaitAction();

    /**
     * The meta object literal for the '<em><b>Duration</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WAIT_ACTION__DURATION = eINSTANCE.getWaitAction_Duration();

    /**
     * The meta object literal for the '<em><b>Unit</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WAIT_ACTION__UNIT = eINSTANCE.getWaitAction_Unit();

    /**
     * The meta object literal for the '{@link org.xtext.example.vitsika.impl.OpenApplicationActionImpl <em>Open Application Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.vitsika.impl.OpenApplicationActionImpl
     * @see org.xtext.example.vitsika.impl.VitsikaPackageImpl#getOpenApplicationAction()
     * @generated
     */
    EClass OPEN_APPLICATION_ACTION = eINSTANCE.getOpenApplicationAction();

    /**
     * The meta object literal for the '<em><b>Applications</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPEN_APPLICATION_ACTION__APPLICATIONS = eINSTANCE.getOpenApplicationAction_Applications();

    /**
     * The meta object literal for the '{@link org.xtext.example.vitsika.impl.MatyImpl <em>Maty</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.vitsika.impl.MatyImpl
     * @see org.xtext.example.vitsika.impl.VitsikaPackageImpl#getMaty()
     * @generated
     */
    EClass MATY = eINSTANCE.getMaty();

    /**
     * The meta object literal for the '<em><b>Proc</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MATY__PROC = eINSTANCE.getMaty_Proc();

    /**
     * The meta object literal for the '{@link org.xtext.example.vitsika.impl.SurferImpl <em>Surfer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.vitsika.impl.SurferImpl
     * @see org.xtext.example.vitsika.impl.VitsikaPackageImpl#getSurfer()
     * @generated
     */
    EClass SURFER = eINSTANCE.getSurfer();

    /**
     * The meta object literal for the '<em><b>Url</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SURFER__URL = eINSTANCE.getSurfer_Url();

    /**
     * The meta object literal for the '{@link org.xtext.example.vitsika.impl.WifiCreateImpl <em>Wifi Create</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.vitsika.impl.WifiCreateImpl
     * @see org.xtext.example.vitsika.impl.VitsikaPackageImpl#getWifiCreate()
     * @generated
     */
    EClass WIFI_CREATE = eINSTANCE.getWifiCreate();

    /**
     * The meta object literal for the '<em><b>Ssid</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WIFI_CREATE__SSID = eINSTANCE.getWifiCreate_Ssid();

    /**
     * The meta object literal for the '<em><b>Passwd</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WIFI_CREATE__PASSWD = eINSTANCE.getWifiCreate_Passwd();

    /**
     * The meta object literal for the '{@link org.xtext.example.vitsika.impl.TypewriteImpl <em>Typewrite</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.vitsika.impl.TypewriteImpl
     * @see org.xtext.example.vitsika.impl.VitsikaPackageImpl#getTypewrite()
     * @generated
     */
    EClass TYPEWRITE = eINSTANCE.getTypewrite();

    /**
     * The meta object literal for the '<em><b>Soratra</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPEWRITE__SORATRA = eINSTANCE.getTypewrite_Soratra();

    /**
     * The meta object literal for the '{@link org.xtext.example.vitsika.impl.WordTypingAutoImpl <em>Word Typing Auto</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.vitsika.impl.WordTypingAutoImpl
     * @see org.xtext.example.vitsika.impl.VitsikaPackageImpl#getWordTypingAuto()
     * @generated
     */
    EClass WORD_TYPING_AUTO = eINSTANCE.getWordTypingAuto();

    /**
     * The meta object literal for the '<em><b>Teny</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WORD_TYPING_AUTO__TENY = eINSTANCE.getWordTypingAuto_Teny();

  }

} //VitsikaPackage
