/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.vitsika;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.vitsika.VitsikaPackage
 * @generated
 */
public interface VitsikaFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  VitsikaFactory eINSTANCE = org.xtext.example.vitsika.impl.VitsikaFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Ataovy Task</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ataovy Task</em>'.
   * @generated
   */
  AtaovyTask createAtaovyTask();

  /**
   * Returns a new object of class '<em>Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Action</em>'.
   * @generated
   */
  Action createAction();

  /**
   * Returns a new object of class '<em>Click Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Click Action</em>'.
   * @generated
   */
  ClickAction createClickAction();

  /**
   * Returns a new object of class '<em>Move Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Move Action</em>'.
   * @generated
   */
  MoveAction createMoveAction();

  /**
   * Returns a new object of class '<em>Wait Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Wait Action</em>'.
   * @generated
   */
  WaitAction createWaitAction();

  /**
   * Returns a new object of class '<em>Open Application Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Open Application Action</em>'.
   * @generated
   */
  OpenApplicationAction createOpenApplicationAction();

  /**
   * Returns a new object of class '<em>Maty</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Maty</em>'.
   * @generated
   */
  Maty createMaty();

  /**
   * Returns a new object of class '<em>Surfer</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Surfer</em>'.
   * @generated
   */
  Surfer createSurfer();

  /**
   * Returns a new object of class '<em>Wifi Create</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Wifi Create</em>'.
   * @generated
   */
  WifiCreate createWifiCreate();

  /**
   * Returns a new object of class '<em>Typewrite</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Typewrite</em>'.
   * @generated
   */
  Typewrite createTypewrite();

  /**
   * Returns a new object of class '<em>Word Typing Auto</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Word Typing Auto</em>'.
   * @generated
   */
  WordTypingAuto createWordTypingAuto();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  VitsikaPackage getVitsikaPackage();

} //VitsikaFactory
