/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.vitsika;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Wait Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.vitsika.WaitAction#getDuration <em>Duration</em>}</li>
 *   <li>{@link org.xtext.example.vitsika.WaitAction#getUnit <em>Unit</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.vitsika.VitsikaPackage#getWaitAction()
 * @model
 * @generated
 */
public interface WaitAction extends Action
{
  /**
   * Returns the value of the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Duration</em>' attribute.
   * @see #setDuration(int)
   * @see org.xtext.example.vitsika.VitsikaPackage#getWaitAction_Duration()
   * @model
   * @generated
   */
  int getDuration();

  /**
   * Sets the value of the '{@link org.xtext.example.vitsika.WaitAction#getDuration <em>Duration</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Duration</em>' attribute.
   * @see #getDuration()
   * @generated
   */
  void setDuration(int value);

  /**
   * Returns the value of the '<em><b>Unit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unit</em>' attribute.
   * @see #setUnit(String)
   * @see org.xtext.example.vitsika.VitsikaPackage#getWaitAction_Unit()
   * @model
   * @generated
   */
  String getUnit();

  /**
   * Sets the value of the '{@link org.xtext.example.vitsika.WaitAction#getUnit <em>Unit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unit</em>' attribute.
   * @see #getUnit()
   * @generated
   */
  void setUnit(String value);

} // WaitAction
