/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.vitsika;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Wifi Create</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.vitsika.WifiCreate#getSsid <em>Ssid</em>}</li>
 *   <li>{@link org.xtext.example.vitsika.WifiCreate#getPasswd <em>Passwd</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.vitsika.VitsikaPackage#getWifiCreate()
 * @model
 * @generated
 */
public interface WifiCreate extends Action
{
  /**
   * Returns the value of the '<em><b>Ssid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ssid</em>' attribute.
   * @see #setSsid(String)
   * @see org.xtext.example.vitsika.VitsikaPackage#getWifiCreate_Ssid()
   * @model
   * @generated
   */
  String getSsid();

  /**
   * Sets the value of the '{@link org.xtext.example.vitsika.WifiCreate#getSsid <em>Ssid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ssid</em>' attribute.
   * @see #getSsid()
   * @generated
   */
  void setSsid(String value);

  /**
   * Returns the value of the '<em><b>Passwd</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Passwd</em>' attribute.
   * @see #setPasswd(String)
   * @see org.xtext.example.vitsika.VitsikaPackage#getWifiCreate_Passwd()
   * @model
   * @generated
   */
  String getPasswd();

  /**
   * Sets the value of the '{@link org.xtext.example.vitsika.WifiCreate#getPasswd <em>Passwd</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Passwd</em>' attribute.
   * @see #getPasswd()
   * @generated
   */
  void setPasswd(String value);

} // WifiCreate
