/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.vitsika;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Word Typing Auto</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.vitsika.WordTypingAuto#getTeny <em>Teny</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.vitsika.VitsikaPackage#getWordTypingAuto()
 * @model
 * @generated
 */
public interface WordTypingAuto extends Action
{
  /**
   * Returns the value of the '<em><b>Teny</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Teny</em>' attribute.
   * @see #setTeny(String)
   * @see org.xtext.example.vitsika.VitsikaPackage#getWordTypingAuto_Teny()
   * @model
   * @generated
   */
  String getTeny();

  /**
   * Sets the value of the '{@link org.xtext.example.vitsika.WordTypingAuto#getTeny <em>Teny</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Teny</em>' attribute.
   * @see #getTeny()
   * @generated
   */
  void setTeny(String value);

} // WordTypingAuto
