/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.Vitsika.ui.internal.VitsikaActivator;

public class VitsikaUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return VitsikaActivator.getInstance().getInjector("org.xtext.example.Vitsika");
	}

}
